version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: goxdb
    volumes:
      - gox_db_disk:/var/lib/postgresql/data

volumes:
  gox_db_disk:
    driver: local
